FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc-aarch64-linux-gnu \
    binutils-aarch64-linux-gnu \
    bison \
    flex \
    libncurses-dev \
    libssl-dev \
    libelf-dev \
    bc \
    git \
    wget \
    cpio \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build
